<?php

/**
 * @file
 * Contains userpoints.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function userpoints_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the userpoints module.
    case 'help.page.userpoints':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;

    default:
  }
}
