userpoints.userpoints_type.*:
  type: config_entity
  label: 'User points type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    initial_value:
      type: float
      label: 'Initial value'
    uuid:
      type: string
